[workspace]

members = [
    "columnq",
    "roapi-http",
]

[patch.crates-io]
arrow = { git = "https://github.com/houqp/arrow.git", rev = "bb6f8e1448f4065c54938b9af92adcf1adeffc47" }
parquet = { git = "https://github.com/houqp/arrow.git", rev = "bb6f8e1448f4065c54938b9af92adcf1adeffc47" }
datafusion = { git = "https://github.com/houqp/arrow.git", rev = "bb6f8e1448f4065c54938b9af92adcf1adeffc47" }

actix-web = { git = "https://github.com/actix/actix-web.git", rev = "b37669cb3b47eeb60c161ff12156d1c877af91a2" }
actix-http = { git = "https://github.com/actix/actix-web.git", rev = "b37669cb3b47eeb60c161ff12156d1c877af91a2" }
awc = { git = "https://github.com/actix/actix-web.git", rev = "b37669cb3b47eeb60c161ff12156d1c877af91a2" }
actix-cors = { git = "https://github.com/houqp/actix-extras.git", rev = "ab3bdb6a5924b6d881d204856199e7539e273d2f" }
