[package]
name = "roapi"
version = "0.1.0"
authors = ["Qingping Hou <dave2008713@gmail.com>"]
edition = "2018"

[lib]
name = "roapi"
path = "src/lib.rs"

[[bin]]
name = "roapi"
path = "src/main.rs"

[dependencies]
arrow = { path = "/home/houqp/Documents/code/delta/arrow/rust/arrow" }
parquet = { path = "/home/houqp/Documents/code/delta/arrow/rust/parquet" }
# datafusion = "3"
datafusion = { path = "/home/houqp/Documents/code/delta/arrow/rust/datafusion" }
actix-web = "3"
actix-cors = "0.4.0"
actix-rt = "1"
actix-service = "*"
actix-http = "*"
env_logger = "0"
log = "0"
serde = "1.0.103"
serde_json = "1.0.44"
serde_derive = "1.0.103"
serde_yaml = "0.8"
clap = { version = ">=3.0.0-beta.2,<4", features = ["color"] }
anyhow = "1"
uriparse = "0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
bytes = { version = "0" }
graphql-parser = "0"
lazy_static = "1"
regex = "1"
sqlparser = "0.7"
lexical-core = "0.7"
thiserror = "1"
yup-oauth2 = "4"  # 5 introduces tokio 1.0
tokio = "0"

[patch.crates-io]
datafusion = { path = "/home/houqp/Documents/code/delta/arrow/rust/datafusion" }
arrow = { path = "/home/houqp/Documents/code/delta/arrow/rust/arrow" }
parquet = { path = "/home/houqp/Documents/code/delta/arrow/rust/parquet" }

[patch."https://github.com/apache/arrow"]
arrow = { path = "/home/houqp/Documents/code/delta/arrow/rust/arrow" }
parquet = { path = "/home/houqp/Documents/code/delta/arrow/rust/parquet" }
# parquet = { path = "/home/houqp/Documents/code/delta/arrow/rust/parquet" }
datafusion = { path = "/home/houqp/Documents/code/delta/arrow/rust/datafusion" }

[features]
simd = ["arrow/simd", "datafusion/simd"]
